id: ID325C552
ocr_import_info:
  timestamp: '2023-09-27T04:30:59.562478+00:00'
  batch_id: batch-0909
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 05:39:02.747664+00:00
last_modified: 2023-09-27 05:39:02.747669+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1466
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1466
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་ཐམས་ཅད་ཀྱི་རྒྱལ་པོ་དཔལ་གསང་བ་འདུས་པའི་རྩ་བའི་རྒྱུད་ཀྱི་སྒྲོན་མ་རབ་ཏུ་གསལ་བར་བྱེད་པའི་རྒྱ་ཆེར་བཤད་པས་འཆད་པ་ལས་ལེའུ་དང་པོ་རྒྱ་ཆེར་བཤད་པ་སོགས།
  languages:
  - bo
  author: རྒྱུད་སྨད་ཤེས་རབ་སེངྒེ
statistics:
  ocr_word_mean_confidence_index: 0.9710109590410322
  ocr_word_median_confidence_index: 0.999791
bases:
  I1NLM1466_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1466_001
      total_pages: 482
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1466_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.999791
      ocr_word_mean_confidence_index: 0.9710109590410322
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
